### ISSUE TITLE
Mortality.mat

### ISSUE THREAD

**Issue by TVect** [RezaSadeghiWSU/Early-Hospital-Mortality-Prediction-using-Vital-Signals#2]
File **AnalysisWavesMortalityCCU.m** use _Mortality.mat_ as an input. But I cannot find the file (_Mortality.mat_).

So could you tell me where i can find the file?

Thx.

**Comment by RezaSadeghiWSU** [comment]
Hi TVect,
Thank you for your interest. I received your request today. I will response in three days.

Regards,
Reza

**Comment by RezaSadeghiWSU** [comment]
TVect,

Please accept my apology for the late response. The requested file is uploaded in the following directory.
https://github.com/RezaSadeghiWSU/Early-Hospital-Mortality-Prediction-using-Vital-Signals/tree/master/Catching%20data%20and%20preprocessing/Requested_Files

Regarding the Catching data and preprocessing step (Access to the waveform data used in the paper), please refer to Issue#1 (https://github.com/RezaSadeghiWSU/Early-Hospital-Mortality-Prediction-using-Vital-Signals/issues/1).

Regards,
Reza

**Comment by RezaSadeghiWSU** [comment]
TVect,

Please accept my apology for the late response. The requested file is uploaded in the following directory:
https://github.com/RezaSadeghiWSU/Early-Hospital-Mortality-Prediction-using-Vital-Signals/tree/master/Catching%20data%20and%20preprocessing/Requested_Files

Regarding the Catching data and preprocessing step (Access to the waveform data used in the paper), please refer to Issue#1 (https://github.com/RezaSadeghiWSU/Early-Hospital-Mortality-Prediction-using-Vital-Signals/issues/1).

Regards,
Reza

**Comment by TVect** [comment]
Thanks! 
:thumbsup:  :thumbsup: :thumbsup:
